export type Member = {
    name: string;
    team: string;
    role: "player" | "goalkeeper" | "pres";
};

export const teamLogo = {
    "AS Camurria": "/teams/as_camurria.png",
    Ludopathikos: "/teams/ludopathikos.png",
    "Roxy Bar": "/teams/roxy_bar.png",
    "FC Tocco": "/teams/fc_tocco.png",
    "Chinesis Gym & Al Gaia": "/teams/chinesis_gym_al_gaia.png",
    Zozzons7: "/teams/zozzons7.png",
    "FC Beck's": "/teams/fc_becks.png",
    Armalions: "/teams/armalions.png",
    "Gli Approvati": "/teams/gli_approvati.png",
    "Q.T. I Tacusam": "/teams/qt_i_tacusam.png",
    "Bar Oscar": "/teams/bar_oscar.png",
    "Fanta-Evento": "/teams/fanta_evento.png",
}

export const MEMBERS: Member[] = [
    { name: "Carmelo Falconieri", team: "AS Camurria", role: "pres" },
    { name: "Salvatore Ciccia", team: "AS Camurria", role: "goalkeeper" },
    { name: "Mattia Falconieri", team: "AS Camurria", role: "player" },
    { name: "Riccardo Rizzo", team: "AS Camurria", role: "player" },
    { name: "Luca Maggio", team: "AS Camurria", role: "player" },
    { name: "Salvatore Mancuso", team: "AS Camurria", role: "player" },
    { name: "Salvatore Banno'", team: "AS Camurria", role: "player" },
    { name: "Carmelo Rosano", team: "AS Camurria", role: "player" },
    { name: "Salvatore Di Manno", team: "AS Camurria", role: "player" },
    { name: "Salvatore Di Stefano", team: "AS Camurria", role: "player" },
    { name: "Dario Tahiru", team: "AS Camurria", role: "player" },
    { name: "Francesco Fasciano", team: "Ludopathikos", role: "pres" },
    { name: "Matteo Miceli", team: "Ludopathikos", role: "goalkeeper" },
    { name: "Giuseppe Crimi", team: "Ludopathikos", role: "player" },
    { name: "Gaetano Rivo", team: "Ludopathikos", role: "player" },
    { name: "Antonio Cascino", team: "Ludopathikos", role: "player" },
    { name: "Giovanni Giangreco", team: "Ludopathikos", role: "player" },
    { name: "Giuseppe La Rocca", team: "Ludopathikos", role: "player" },
    { name: "Flavio Leggio", team: "Ludopathikos", role: "player" },
    { name: "Antonio Laneri", team: "Ludopathikos", role: "player" },
    { name: "Vincenzo Giunta", team: "Roxy Bar", role: "pres" },
    { name: "Amedeo Demetrico", team: "Roxy Bar", role: "goalkeeper" },
    { name: "Raffaele Ipsale", team: "Roxy Bar", role: "player" },
    { name: "Daniele Mazzola", team: "Roxy Bar", role: "player" },
    { name: "Soulemana", team: "Roxy Bar", role: "player" },
    { name: "Angelo Messina", team: "Roxy Bar", role: "player" },
    { name: "Matteo Ipsale", team: "Roxy Bar", role: "player" },
    { name: "Raphael Gardali", team: "Roxy Bar", role: "player" },
    { name: "Dario Castellana", team: "Roxy Bar", role: "player" },
    { name: "Flavio Mugavero", team: "FC Tocco", role: "pres" },
    { name: "Vincenzo Proietto", team: "FC Tocco", role: "goalkeeper" },
    { name: "Salvatore Bertolo", team: "FC Tocco", role: "player" },
    { name: "Giuseppe Costa", team: "FC Tocco", role: "player" },
    { name: "Alessandro Russo", team: "FC Tocco", role: "player" },
    { name: "Federico Salamone", team: "FC Tocco", role: "player" },
    { name: "Giuseppe Banno", team: "FC Tocco", role: "player" },
    { name: "Giuseppe Di Manno", team: "FC Tocco", role: "player" },
    { name: "Luigi Silicato", team: "FC Tocco", role: "player" },
    { name: "Mauro Caruso", team: "Chinesis Gym & Al Gaia", role: "pres" },
    { name: "Giacomo Giangreco", team: "Chinesis Gym & Al Gaia", role: "goalkeeper" },
    { name: "Luigi Spataro", team: "Chinesis Gym & Al Gaia", role: "player" },
    { name: "Carmelo Di Blanca", team: "Chinesis Gym & Al Gaia", role: "player" },
    { name: "Federico Ilardo", team: "Chinesis Gym & Al Gaia", role: "player" },
    { name: "Vincenzo Giunta", team: "Chinesis Gym & Al Gaia", role: "player" },
    { name: "Fabio Lavenia", team: "Chinesis Gym & Al Gaia", role: "player" },
    { name: "Salvatore Screpis", team: "Chinesis Gym & Al Gaia", role: "player" },
    { name: "Salvo Licata", team: "Chinesis Gym & Al Gaia", role: "player" },
    { name: "Giovanni Panvini", team: "Chinesis Gym & Al Gaia", role: "player" },
    { name: "Carmelo Romano", team: "Chinesis Gym & Al Gaia", role: "player" },
    { name: "Giuseppe Germanà", team: "Chinesis Gym & Al Gaia", role: "player" },
    { name: "Gabriele Leonforte", team: "Zozzons7", role: "pres" },
    { name: "Cristian Valenti", team: "Zozzons7", role: "goalkeeper" },
    { name: "Daniele Valenti", team: "Zozzons7", role: "player" },
    { name: "Giacomo Trovato", team: "Zozzons7", role: "player" },
    { name: "Jacopo Bivona", team: "Zozzons7", role: "player" },
    { name: "Vincenzo Manuele", team: "Zozzons7", role: "player" },
    { name: "Giovanni Leonforte", team: "Zozzons7", role: "player" },
    { name: "Luigi Torcetta", team: "Zozzons7", role: "player" },
    { name: "Davide Sineri", team: "Zozzons7", role: "player" },
    { name: "Nunzio Pirronitto", team: "Zozzons7", role: "player" },
    { name: "Andrea Faraci", team: "Zozzons7", role: "player" },
    { name: "Gaetano Marchese", team: "FC Beck's", role: "pres" },
    { name: "Riccardo Greco", team: "FC Beck's", role: "goalkeeper" },
    { name: "Giuseppe Salimeni", team: "FC Beck's", role: "player" },
    { name: "Emanuel Scaminaci", team: "FC Beck's", role: "player" },
    { name: "Flavio Granata", team: "FC Beck's", role: "player" },
    { name: "Manuel Sinato'", team: "FC Beck's", role: "player" },
    { name: "Rosario Arena", team: "FC Beck's", role: "player" },
    { name: "Fernando Garofalo", team: "FC Beck's", role: "player" },
    { name: "Francesco Gravagna", team: "FC Beck's", role: "player" },
    { name: "Davide Maurizi", team: "Armalions", role: "pres" },
    { name: "Emanuele Catalfo", team: "Armalions", role: "goalkeeper" },
    { name: "Marco Maurizi", team: "Armalions", role: "player" },
    { name: "Cesare Giangrasso", team: "Armalions", role: "player" },
    { name: "Salvatore Paviano", team: "Armalions", role: "player" },
    { name: "Nino Marsiglione", team: "Armalions", role: "player" },
    { name: "Mattia Catalfo", team: "Armalions", role: "player" },
    { name: "Simone Maurizi", team: "Armalions", role: "player" },
    { name: "Giovanni Smario", team: "Armalions", role: "player" },
    { name: "Alex Milazzotto", team: "Armalions", role: "player" },
    { name: "Gaetano Arangio", team: "Gli Approvati", role: "pres" },
    { name: "Gaetano D'Agostino", team: "Gli Approvati", role: "goalkeeper" },
    { name: "Francesco Proto", team: "Gli Approvati", role: "player" },
    { name: "Andrea Gandolfo", team: "Gli Approvati", role: "player" },
    { name: "Federico Drago", team: "Gli Approvati", role: "player" },
    { name: "Benito Roberti", team: "Gli Approvati", role: "player" },
    { name: "Salvatore Marraffino", team: "Gli Approvati", role: "player" },
    { name: "Stefano Barbera", team: "Gli Approvati", role: "player" },
    { name: "Mattia Anselmo", team: "Gli Approvati", role: "player" },
    { name: "Epifanio Giunta", team: "Q.T. I Tacusam", role: "pres" },
    { name: "Liborio Vaccalluzzo", team: "Q.T. I Tacusam", role: "goalkeeper" },
    { name: "Mario Ilardi", team: "Q.T. I Tacusam", role: "player" },
    { name: "Giancarlo Catania", team: "Q.T. I Tacusam", role: "player" },
    { name: "Andrea Paolocà", team: "Q.T. I Tacusam", role: "player" },
    { name: "Cristian Patti", team: "Q.T. I Tacusam", role: "player" },
    { name: "Giacomo Catania", team: "Q.T. I Tacusam", role: "player" },
    { name: "Ones Cristaldi", team: "Q.T. I Tacusam", role: "player" },
    { name: "Salvatore Paviano", team: "Q.T. I Tacusam", role: "player" },
    { name: "Marco Traversa", team: "Q.T. I Tacusam", role: "player" },
    { name: "Alberto Cascino", team: "Q.T. I Tacusam", role: "player" },
    { name: "Giuseppe \"A Flaca\" La Ferrara", team: "Bar Oscar", role: "pres" },
    { name: "Antonio Blando", team: "Bar Oscar", role: "goalkeeper" },
    { name: "Armando Ilardi", team: "Bar Oscar", role: "player" },
    { name: "Toni Mazzola", team: "Bar Oscar", role: "player" },
    { name: "Santi Giunta", team: "Bar Oscar", role: "player" },
    { name: "Corrado Conti", team: "Bar Oscar", role: "player" },
    { name: "Gaetano Gervasi", team: "Bar Oscar", role: "player" },
    { name: "Filippo Di Leonforte", team: "Bar Oscar", role: "player" },
    { name: "Ones Rindone", team: "Bar Oscar", role: "player" },
    { name: "Roberto Arangio", team: "Fanta-Evento", role: "pres" },
    { name: "Gaetano Smario", team: "Fanta-Evento", role: "goalkeeper" },
    { name: "Ettore Speranza", team: "Fanta-Evento", role: "player" },
    { name: "Filippo Cocuzza", team: "Fanta-Evento", role: "player" },
    { name: "Filippo Milazzotto", team: "Fanta-Evento", role: "player" },
    { name: "Alfonso Panvini", team: "Fanta-Evento", role: "player" },
    { name: "Domenico Venticinque", team: "Fanta-Evento", role: "player" },
    { name: "Simone Riverà", team: "Fanta-Evento", role: "player" },
    { name: "Rosario Calabrese", team: "Fanta-Evento", role: "player" },
];
